run:
  deadline: 5m
  tests: false
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - interfacer # deprecated
    - maligned # deprecated
    - scopelint # deprecated
    - golint # deprecated

linters-settings:
  cyclop:
    max-complexity: 12
