run:
  deadline: 5m
  tests: false
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - nolintlint
    - scopelint # deprecated
    - golint # deprecated
    - maligned # deprecated
    - interfacer # deprecated
    - ireturn
    - goerr113
    - wsl
    - godot
    - gocritic
    - varnamelen
    - nlreturn
    - gomnd
    - exhaustivestruct
    - lll
    - gofumpt
    - funlen
    - cyclop
    - gocognit
