language: go

go:
  - 1.13.15
  - 1.14.14
  - 1.15.7
  - tip

script:
  - go build
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
